name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
          registry-url: "https://registry.npmjs.org"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.21.0

      - name: Install dependency
        run: pnpm install

      - name: Pnpm build
        run: pnpm build

      - name: Publish to NPM
        run: |
          pnpm config set https://registry.npmjs.org/:_authToken=$NPM_TOKEN
          pnpm -r publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
